version: 1.0.0

client:
  organization: org1
  logging:
    level: info

  cryptoconfig:
    path: /usr/local/hyper/test2/configtx

  credentialStore:
    path: "/tmp/channel-store"
    cryptoStore:
      path: /tmp/channel-msp

  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

  tlsCerts:
    systemCertPool: true
    client:
      keyfile: /usr/local/hyper/test2/crypto-config/peerOrganizations/org1/users/Admin@org1/tls-msp/keystore/key.pem
      certfile: /usr/local/hyper/test2/crypto-config/peerOrganizations/org1/users/Admin@org1/tls-msp/signcerts/cert.pem

channels:
  mychannel:
    orderers:
      - orderer1-org0
    peers:
      peer1-org1:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    #      peer2-org1:
    #        endorsingPeer: true
    #        chaincodeQuery: true
    #        ledgerQuery: true
    #        eventSource: true
    #
    #      peer1-org2:
    #        endorsingPeer: true
    #        chaincodeQuery: true
    #        ledgerQuery: true
    #        eventSource: true
    #
    #      peer2-org2:
    #        endorsingPeer: true
    #        chaincodeQuery: true
    #        ledgerQuery: true
    #        eventSource: true

    policies:
      queryChannelConfig:
        minResponses: 1
        maxTargets: 1
        retryOpts:
          attempts: 5
          initialBackoff: 500ms
          maxBackoff: 5s
          backoffFactor: 2.0
#      eventService:
#        resolverStrategy: PreferOrg
#        balancer: Random
#        blockHeightLagThreshold: 5
#        reconnectBlockHeightLagThreshold: 10
#        peerMonitorPeriod: 5s



organizations:
  org1:
    mspid: org1MSP
    cryptoPath: /usr/local/hyper/test2/crypto-config/peerOrganizations/org1/users/Admin@org1/msp
    peers:
      - peer1-org1
      - peer2-org1
    certificateAuthorities:
      - ca-org1

  org2:
    mspid: org2MSP
    cryptoPath: /usr/local/hyper/test2/crypto-config/peerOrganizations/org1/users/Admin@org1/msp
    peers:
      - peer1-org2
      - peer2-org2
    certificateAuthorities:
      - ca-org2

  org0:
    mspID: org0MSP
    cryptoPath: /usr/local/hyper/test2/crypto-config/ordererOrganizations/org0/admin/msp

orderers:
  orderer1-org0:
    url: grpcs://192.168.175.145:17050
    grpcOptions:
      ssl-target-name-override: orderer1-org0
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: true
      allow-insecure: true
    tlsCACerts:
      path: /usr/local/hyper/test2/crypto-config/ordererOrganizations/org0/orderers/orderer1-org0/tls-msp/tlscacerts/tls-0-0-0-0-17052.pem

peers:
  peer1-org1:
    url: grpcs://192.168.175.145:17051
    grpcOptions:
      ssl-target-name-override: peer1-org1
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: true
      allow-insecure: true
    tlsCACerts:
      path: /usr/local/hyper/test2/crypto-config/peerOrganizations/org1/peers/peer1/tls-msp/tlscacerts/tls-0-0-0-0-17052.pem

  peer2-org1:
    url: grpcs://192.168.175.145:18051
    grpcOptions:
      ssl-target-name-override: peer2-org1
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: true
      allow-insecure: true
    tlsCACerts:
      path: /usr/local/hyper/test2/crypto-config/peerOrganizations/org1/peers/peer2/tls-msp/tlscacerts/tls-0-0-0-0-17052.pem

  peer1-org2:
    url: grpcs://192.168.175.145:19051
    grpcOptions:
      ssl-target-name-override: peer1-org2
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: true
      allow-insecure: true
    tlsCACerts:
      path: /usr/local/hyper/test2/crypto-config/peerOrganizations/org2/peers/peer1/tls-msp/tlscacerts/tls-0-0-0-0-17052.pem

  peer2-org2:
    url: grpcs://192.168.175.145:10051
    grpcOptions:
      ssl-target-name-override: peer2-org2
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: true
      allow-insecure: true
    tlsCACerts:
      path: /usr/local/hyper/test2/crypto-config/peerOrganizations/org2/peers/peer2/tls-msp/tlscacerts/tls-0-0-0-0-17052.pem

entityMatchers:
  peer:
    - pattern: (\w*)peer1-org1(\w*)
      urlsubstitutionexp: grpcs://192.168.175.145:17051
      ssltargetoverrideurlsubstitutionexp: peer1-org1
      mappedhost: peer1-org1

    - pattern: (\w*)peer2-org1(\w*)
      urlsubstitutionexp: grpcs://192.168.175.145:18051
      ssltargetoverrideurlsubstitutionexp: peer2-org1
      mappedhost: peer2-org1

    - pattern: (\w*)peer1-org2(\w*)
      urlsubstitutionexp: grpcs://192.168.175.145:19051
      ssltargetoverrideurlsubstitutionexp: peer1-org2
      mappedhost: peer1-org2

    - pattern: (\w*)peer2-org2(\w*)
      urlsubstitutionexp: grpcs://192.168.175.145:10051
      ssltargetoverrideurlsubstitutionexp: peer2-org2
      mappedhost: peer2-org2

  orderer:
    - pattern: (\w*)orderer1-org0(\w*)
      urlsubstitutionexp: grpcs://192.168.175.145:17050
      ssltargetoverrideurlsubstitutionexp: orderer1-org0
      mappedhost: orderer1-org0

certificateAuthorities:
  ca-org2:
    url: https://0.0.0.0:17055
    tlsCACerts:
      path: /usr/local/hyper/test2/crypto-config/peerOrganizations/org2/ca/ca-cert.pem
      client:
        key:
          path: /usr/local/hyper/test2/configtx/org2/msp/keystore/key.pem
        cert:
          path: /usr/local/hyper/test2/configtx/org2/msp/signcerts/cert.pem

    registrar:
      enrollId: ca-org2-admin
      enrollSecret: ca-org2-adminpw

  ca-org1:
    url: https://0.0.0.0:17054
    tlsCACerts:
      path: /usr/local/hyper/test2/crypto-config/peerOrganizations/org1/ca/ca-cert.pem
      client:
        key:
          path: /usr/local/hyper/test2/configtx/org1/msp/keystore/key.pem
        cert:
          path: /usr/local/hyper/test2/configtx/org1/msp/signcerts/cert.pem

    registrar:
      enrollId: ca-org1-admin
      enrollSecret: ca-org1-adminpw
